name: Josh Robinson
favicon: null
layout_spectrum: 0.8997028027661145
typography_spectrum: 0.2884069567080587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3005063042510301
  lightness: 0.9585472934413701
  saturation: 0.5193662319798023
  rhythmicContrast: 0.5947338531259447
purpose: []
